import type { Metadata } from "next";
import { Zen_Maru_Gothic } from "next/font/google";
import "./globals.css";
import classNames from "classnames";

const geistMono = Zen_Maru_Gothic({
  weight: "400",
  variable: "--font-zen-maru-gothic",
  subsets: [],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={classNames("min-h-screen bg-base-200", geistMono.className)}
      >
        {children}
      </body>
    </html>
  );
}
